
        name: Nest.js CI

        on: [push]
       
        
        jobs:
          test:
            runs-on: ubuntu-latest
        
            steps:
              - uses: actions/checkout@v2
        
              - name: Use Node.js
                uses: actions/setup-node@v2
                with:
                  node-version: '20'
        
              - name: Install dependencies
                run: npm install
        
              - name: Run Jest
                run: npm test
        
              - name: Check coverage
                run: |
                  COVERAGE_THRESHOLD=90
                  ACTUAL_COVERAGE=$(grep -E 'Statements|Branches|Functions|Lines' coverage/lcov.info | awk '{print $3}' | awk -F "%" '{print $1}')
                  echo "Actual coverage is $ACTUAL_COVERAGE%"
                  if [ $ACTUAL_COVERAGE -lt $COVERAGE_THRESHOLD ]; then
                    echo "Coverage is below threshold. Exiting with code 1."
                    exit 1
                  fi
        
              - name: Upload coverage report
                uses: actions/upload-artifact@v2
                with:
                  name: coverage
                  path: coverage
        